[build-system]
requires = ["flit_core >=3.2,<4",
            "myst_parser<=0.18.0"]
build-backend = "flit_core.buildapi"

[project]
name = "NYU Greene HPC"
authors = [{name = "Anant Singh", email = "anant.singh@nyu.edu"}]
dynamic = ["0.1.0", "A guide to work with NYU Greene HPC"]
